name: OpenFL Android

on:
  workflow_dispatch:  # allows manual runs
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup NDK r21e
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r21e

    - name: Setup Haxe 4.2.5
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.5

    - name: Install Haxelib dependencies
      run: |
        haxelib install lime --quiet
        haxelib install openfl --quiet
        haxelib install hxcpp 4.2.1 --quiet
        haxelib install starling --quiet

    - name: Setup Java 11
      uses: actions/setup-java@v4
      with:
        java-version: "11"
        distribution: "temurin"

    - name: Lime Android setup
      run: |
        haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
        haxelib run lime config ANDROID_NDK_ROOT ${{ steps.setup-ndk.outputs.ndk-path }}
        haxelib run lime config JAVA_HOME ${{ env.JAVA_HOME }}
        haxelib run lime config ANDROID_SETUP true
        haxelib run lime config

    - name: Build release APK (32-bit + 64-bit)
      run: |
        haxelib run openfl build android -release

    - name: List build output
      run: ls -R Export/android/bin || true

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: FootNote-android-apk
        path: |
          Export/android/bin/app/build/outputs/apk/debug/*.apk
          Export/android/bin/app/build/outputs/apk/release/*.apk
